<?php
/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */

// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  'built_in_version' => '7.7.1.2',
  'acceptable_sugar_versions' => 
  array (
    0 => '',
  ),
  'acceptable_sugar_flavors' => 
  array (
    0 => 'PRO',
    1 => 'CORP',
    2 => 'ENT',
    3 => 'ULT',
  ),
  'readme' => '',
  'key' => 'bus',
  'author' => 'Admin',
  'description' => '',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'BusSystemPackage',
  'published_date' => '2017-08-28 09:09:58',
  'type' => 'module',
  'version' => 1503911398,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'BusSystemPackage',
  'beans' => 
  array (
    0 => 
    array (
      'module' => 'bus_BusManagment',
      'class' => 'bus_BusManagment',
      'path' => 'modules/bus_BusManagment/bus_BusManagment.php',
      'tab' => true,
    ),
    1 => 
    array (
      'module' => 'bus_Passenger',
      'class' => 'bus_Passenger',
      'path' => 'modules/bus_Passenger/bus_Passenger.php',
      'tab' => true,
    ),
  ),
  'layoutdefs' => 
  array (
  ),
  'relationships' => 
  array (
  ),
  'image_dir' => '<basepath>/icons',
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/bus_BusManagment',
      'to' => 'modules/bus_BusManagment',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/bus_Passenger',
      'to' => 'modules/bus_Passenger',
    ),
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
  ),
);