<?php /* Smarty version 2.6.11, created on 2017-08-28 11:49:46
         compiled from modules/ModuleBuilder/tpls/MBModule/Class.tpl */ ?>
<?php echo '<?php'; ?>

/*
 * Your installation or use of this SugarCRM file is subject to the applicable
 * terms available at
 * http://support.sugarcrm.com/06_Customer_Center/10_Master_Subscription_Agreements/.
 * If you do not agree to all of the applicable terms or do not have the
 * authority to bind the entity as an authorized representative, then do not
 * install or use this SugarCRM file.
 *
 * Copyright (C) SugarCRM Inc. All rights reserved.
 */
/**
 * THIS CLASS IS GENERATED BY MODULE BUILDER
 * PLEASE DO NOT CHANGE THIS CLASS
 * PLACE ANY CUSTOMIZATIONS IN <?php echo $this->_tpl_vars['class']['name']; ?>

 */

<?php $_from = $this->_tpl_vars['class']['requires']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['require']):
?>
require_once '<?php echo $this->_tpl_vars['require']; ?>
';
<?php endforeach; endif; unset($_from); ?>

class <?php echo $this->_tpl_vars['class']['name']; ?>
_sugar extends <?php echo $this->_tpl_vars['class']['extends']; ?>
 {
    public $new_schema = true;
    public $module_dir = '<?php echo $this->_tpl_vars['class']['name']; ?>
';
    public $object_name = '<?php echo $this->_tpl_vars['class']['name']; ?>
';
    public $table_name = '<?php echo $this->_tpl_vars['class']['table_name']; ?>
';
    public $importable = <?php if ($this->_tpl_vars['class']['importable']): ?>true<?php else: ?>false<?php endif; ?>;
<?php $_from = $this->_tpl_vars['class']['fields']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['field'] => $this->_tpl_vars['def']):
?>
    public $<?php echo $this->_tpl_vars['field']; ?>
;
<?php endforeach; endif; unset($_from); ?>
    <?php if (empty ( $this->_tpl_vars['class']['team_security'] )): ?>
    public $disable_row_level_security = true;
    <?php endif; ?>

    /**
     * @deprecated Use __construct() instead
     */
    public function <?php echo $this->_tpl_vars['class']['name']; ?>
_sugar()
    {
        self::__construct();
    }

    /**
     * Constructor
     */
    public function __construct()
    {
        parent::__construct();
    }

<?php if ($this->_tpl_vars['class']['acl']): ?>
    public function bean_implements($interface){
        switch($interface){
            case 'ACL': return true;
        }
        return false;
    }
<?php endif; ?>
    
}